name: Testing

on:
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.16.x
        os:
          - ubuntu-18.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set up ssh agent
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.CICD_RSA_KEY }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Bytecode Version
        id: bytecode_version
        run: echo ::set-output name=VERSION::$(cat contract-artifacts/version-config.json | jq -r '.gateway')

      - name: Download Bytecode
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: axelarnetwork/solidity-cgp-gateway
          workflow: publish-bytecode.yaml
          name: Bytecode-${{ steps.bytecode_version.outputs.VERSION }}
          path: contract-artifacts/gateway

      - name: Populate Bytecode
        run: |
          bash scripts/populate-bytecode.sh

      - name: Test
        run: |
          git config --global url."git@github.com:axelarnetwork".insteadOf https://github.com/axelarnetwork

          go test ./...
